// Содержание сайта. Все факты и цифры взяты из резюме Евгения Шутова.
// Ничего не выдумано: если данных нет — поля нет.

export const shared = {
  phone: '+7 929 773-11-04',
  phoneHref: '+79297731104',
  email: 'mail@e-shutov.ru',
  telegram: '@Taback_1028',
  telegramHref: 'https://t.me/Taback_1028',
  domain: 'https://e-shutov.ru',
  years: '2026',
};

export const ru = {
  lang: 'ru',
  dir: 'ltr',
  altLang: 'en',
  altLabel: 'English',
  altHref: '/en/',
  homeHref: '/',
  title: 'Евгений Шутов — международные проекты, делегации и деловые мероприятия',
  description:
    'Специалист-международник, МГИМО. Латинская Америка, португальский и английский C1. Сопровождение иностранных делегаций, организация деловых мероприятий, договоры и отчётность по государственным контрактам.',
  ogLocale: 'ru_RU',

  brand: 'Шутов',
  skip: 'Перейти к содержанию',
  menu: 'Меню',
  close: 'Закрыть',
  cvLabel: 'Резюме PDF',

  nav: [
    { href: '#profile', label: 'О себе', n: '01' },
    { href: '#practice', label: 'Направления', n: '02' },
    { href: '#geo', label: 'География', n: '03' },
    { href: '#work', label: 'Проекты', n: '04' },
    { href: '#current', label: '2026', n: '05' },
    { href: '#career', label: 'Опыт', n: '06' },
    { href: '#contact', label: 'Контакты', n: '07' },
  ],

  hero: {
    eyebrow: 'Евгений Шутов',
    lead: 'Международные проекты,',
    leadEm: 'делегации',
    leadTail: 'и деловые мероприятия',
    para:
      'Руководитель российского офиса Consult Invest ITIC. Латинская Америка, португальский и английский C1 — переговоры и документы без переводчика.',
    ctaPrimary: 'Написать',
    ctaSecondary: 'Смотреть проекты',
    portraitAlt: 'Евгений Шутов',
  },

  figures: {
    eyebrow: 'Проверяемые результаты',
    items: [
      { value: '45', unit: 'человек', label: 'В пяти национальных делегациях «Интервидения-2025», которые я вёл от приглашения до отъезда' },
      { value: '134', unit: 'страны', label: 'Охват сигнала бразильской трансляции, которую я организовал самостоятельно' },
      { value: '9', unit: 'млн ₽', label: 'Расходы по государственному контракту, которые я свёл в отчёт с первичными документами' },
      { value: '677', unit: 'предприятий', label: 'Охвачено в России, Узбекистане и Казахстане при плане 300–400 за три месяца' },
    ],
  },

  profile: {
    n: '01',
    kicker: 'О себе',
    title: 'Работаю там, где нужен прямой разговор без переводчика',
    paras: [
      'Международный проект держится на трёх вещах: подписанный договор, делегация, которая приехала и уехала без сбоев, и отчёт, принятый государственным заказчиком. Я отвечаю за все три.',
      'Основной рабочий язык — португальский: МГИМО, первый иностранный, уровень C1 в дипломатической, юридической и коммерческой лексике. С латиноамериканской стороной я говорю напрямую, без переводчика, и это заметно сокращает сроки согласований.',
      'Вторая половина работы — операционная и финансовая: программа визита, визы, подрядчики, площадка, приём платежей, закрывающие документы и отчётность. Я одинаково спокойно веду переговоры с министерством и свожу первичные документы на девять миллионов рублей.',
    ],
    facts: [
      {
        k: 'Образование',
        v: 'МГИМО, «Международные отношения», бакалавр с отличием. Магистратура «Экономика» — международный финансовый анализ, учёт и аудит.',
      },
      {
        k: 'Языки',
        v: 'Португальский C1, английский C1, испанский B1. Летняя школа по бразилистике в Федеральном университете Минас-Жерайс.',
      },
      {
        k: 'Регион',
        v: 'Латинская Америка, прежде всего Бразилия. Дипломная работа — экономическая дипломатия Бразилии как инструмент внешней политики.',
      },
      {
        k: 'Практика',
        v: 'Телевидение, государственные ведомства и частные компании. Проекты по указу Президента, при поддержке МИД и по государственным контрактам.',
      },
    ],
  },

  practice: {
    n: '02',
    kicker: 'Направления',
    title: 'Что я делаю',
    intro: 'Пять направлений. В каждом есть законченные проекты, а не только строки в должностной инструкции.',
    items: [
      {
        t: 'Иностранные делегации и протокол',
        d: 'Сопровождение делегации от первого письма в министерство до отъезда группы.',
        b: ['Договоры соорганизатора с правительствами стран', 'Визовая поддержка, размещение, транспорт', 'Программа пребывания и атташе делегаций', 'Работа с посольствами и государственными ведомствами'],
      },
      {
        t: 'Организация международных мероприятий',
        d: 'Форумы, конкурсы и акселерационные программы: полный цикл от концепции до закрывающих документов.',
        b: ['Деловая программа и отбор участников', 'Продажи и привлечение участников', 'Площадка, проживание, подрядчики', 'Приём платежей и договорная база'],
      },
      {
        t: 'Договоры, закупки и отчётность',
        d: 'Документы проекта — от договоров с подрядчиками до отчёта по государственному контракту.',
        b: ['Отчётность по государственным контрактам', 'Сверка договоров с подрядчиками и первичных документов', 'Агентские договоры, акты, коммерческие предложения', 'Кадровое делопроизводство и комплаенс'],
      },
      {
        t: 'Развитие бизнеса и выход на рынки',
        d: 'Привлечение клиентов на рынках России и СНГ с измеримыми показателями.',
        b: ['Лидогенерация и холодные продажи', 'CRM по странам', 'Исследование рынка и конкурентный анализ', 'Финансовое моделирование и юнит-экономика'],
      },
      {
        t: 'Язык и перевод',
        d: 'Португальский и английский в дипломатической, юридической, коммерческой и технической лексике.',
        b: ['Последовательный перевод на форумах', 'Перевод договоров, регламентов и уставных документов', 'Техническая документация', 'Деловая и дипломатическая переписка'],
      },
    ],
  },

  geo: {
    n: '03',
    kicker: 'География',
    title: 'Где я работал',
    intro: 'Двенадцать стран, в которых у меня были проекты, переговоры или делегации. Номера на карте совпадают с номерами в списке.',
    legendMarked: 'Страны проектов',
    legendRest: 'Остальной мир',
    items: [
      { key: 'Brazil', name: 'Бразилия', note: 'Делегация «Интервидения», трансляция на бразильском телевидении, фестиваль молодёжи, обращение в Министерство туризма' },
      { key: 'Russia', name: 'Россия', note: 'База, Москва. Российское направление Consult Invest ITIC, форумы и государственные контракты' },
      { key: 'United Arab Emirates', name: 'ОАЭ', note: 'Делегация «Интервидения-2025»; экономическая зона Рас-эль-Хайма' },
      { key: 'Saudi Arabia', name: 'Саудовская Аравия', note: 'Russia Bridge Program, «Интервидение-2026» в Эр-Рияде' },
      { key: 'Ethiopia', name: 'Эфиопия', note: 'Делегация «Интервидения-2025»' },
      { key: 'Kenya', name: 'Кения', note: 'Делегация «Интервидения-2025»' },
      { key: 'Madagascar', name: 'Мадагаскар', note: 'Делегация «Интервидения-2025»' },
      { key: 'China', name: 'Китай', note: 'Документы по запуску офиса в Шэньчжэне' },
      { key: 'Uzbekistan', name: 'Узбекистан', note: 'Привлечение клиентов для RAKEZ, работа с AKFA Group' },
      { key: 'Kazakhstan', name: 'Казахстан', note: 'Привлечение клиентов для RAKEZ' },
      { key: 'India', name: 'Индия', note: 'Делегация форума AGORA' },
      { key: 'South Africa', name: 'ЮАР', note: 'Делегация форума AGORA' },
    ],
  },

  work: {
    n: '04',
    kicker: 'Избранные проекты',
    title: 'Что сделано',
    items: [
      {
        t: 'Интервидение-2025',
        img: 'work-intervision.jpg',
        imgAlt: 'Делегации на «Интервидении-2025»',
        sub: 'Международный музыкальный конкурс',
        meta: 'август — сентябрь 2025 · Live Arena, Москва',
        role: 'Проектный менеджер национальных делегаций',
        d: 'Пришёл на проект меньше чем за месяц до конкурса как специалист со знанием португальского языка. Конкурс проводился по указу Президента при поддержке МИД России, зал на 20 000 мест.',
        b: [
          'Пять национальных делегаций — Бразилия, Мадагаскар, Кения, Эфиопия, ОАЭ — общей численностью 45 человек.',
          'Договоры соорганизатора с правительствами стран, визовая поддержка, размещение, транспорт и десятидневная программа пребывания.',
          'Отобрал и курировал пять атташе делегаций, по одному на страну.',
          'Всю работу с бразильской стороной вёл на португальском: артист, продюсерская команда, телевещатель, министерство культуры.',
          'Самостоятельно организовал трансляцию конкурса на бразильском телевидении: подготовил и перевёл пакет документов для вещателя — устав организации, кадровые документы, соглашения и меморандумы.',
        ],
        m: [
          { v: '45', l: 'членов делегаций' },
          { v: '5', l: 'стран' },
          { v: '3+ млн', l: 'зрителей трансляции' },
          { v: '134', l: 'страны охвата' },
        ],
      },
      {
        t: 'Бизнес-инкубатор ШОС 2025',
        img: 'work-sco.jpg',
        imgAlt: 'Бизнес-инкубатор ШОС, Омск',
        sub: 'Государственный контракт: отчётность и финансовый аудит',
        meta: 'сентябрь — декабрь 2025 · программа в Омске',
        role: 'Руководитель отчётности по государственному контракту',
        d: 'Заказчик — Дирекция Всемирного фестиваля молодёжи. Программа прошла 19–23 августа 2025 года, в ней участвовали больше 100 человек из всех десяти государств — членов ШОС.',
        b: [
          'Итоговый отчёт больше чем на 3 000 страниц: собрал, структурировал и оформил учебные материалы по 25 воркшоп-сессиям.',
          'Конспекты и раздаточные материалы примерно для 12 сессий написал с нуля — исходных материалов не существовало.',
          'Единолично вёл финансовую отчётность: сверил около 10 договоров с подрядчиками — переводчики, кейтеринг, персонал, логистика.',
          'Согласовал корректировки документов с поставщиками и подготовил полностью сбалансированный отчёт о расходах на 9 млн рублей с первичными документами и внутренними приказами.',
        ],
        m: [
          { v: '3 000+', l: 'страниц отчёта' },
          { v: '9 млн ₽', l: 'сведено в отчёте' },
          { v: '25', l: 'воркшоп-сессий' },
          { v: '10', l: 'государств ШОС' },
        ],
      },
      {
        t: 'Russia Bridge Program',
        img: 'work-bridge.jpg',
        imgAlt: 'Russia Bridge Program, Москва',
        sub: 'Первая российско-саудовская программа бизнес-акселерации',
        meta: 'ноябрь — декабрь 2025 · Москва',
        role: 'Соорганизатор',
        d: 'Программа прошла 4–5 декабря 2025 года, в ней участвовали больше 60 человек. Открывали её председатель Комитета Государственной Думы по международным делам Леонид Слуцкий и посол Саудовской Аравии.',
        b: [
          'Продажи и привлечение: около 200 звонков и порядка 1 000 показов в Telegram и в интернете.',
          'Привлёк 30 платных участников и организовал 15 деловых встреч между российскими и иностранными компаниями.',
          'Отобрал 9 российских проектов для питч-сессии; три из них получили прямую инвестиционную поддержку и освобождение от платы за коммерческую лицензию от венчурного фонда Value Makers Studio.',
          'Согласовал договоры по площадке и проживанию с московскими отелями и добился ставок ниже рыночных и дополнительных скидок.',
          'Настроил приём платежей, подготовил шаблоны коммерческих предложений и договоры оказания услуг.',
          'Вёл всю переписку и переговоры с приехавшей саудовской делегацией на английском языке.',
        ],
        m: [
          { v: '60+', l: 'участников' },
          { v: '30', l: 'платных участников' },
          { v: '15', l: 'деловых встреч' },
          { v: '3', l: 'проекта с инвестициями' },
        ],
      },
      {
        t: 'RAKEZ',
        img: 'work-rakez.jpg',
        imgAlt: 'Работа по проекту RAKEZ',
        sub: 'Экономическая зона Рас-эль-Хайма, ОАЭ · рынки России и СНГ',
        meta: 'январь — май 2026',
        role: 'Привлечение клиентов и единая точка контакта',
        d: 'Отвечал за привлечение клиентов на рынках России и СНГ для свободной экономической зоны ОАЭ и был единой точкой контакта для всех российских и СНГ-контрагентов от лица RAKEZ.',
        b: [
          'Охватил около 677 предприятий в России, Узбекистане и Казахстане при плане 300–400 за три месяца.',
          'Получил около 313 откликов с первичным интересом при плановом показателе 300.',
          'Разработал и провёл кампанию холодных продаж: 512 отобранных предприятий, около 275 содержательных ответов.',
          'Выстроил отдельную базу клиентов по каждой из трёх стран.',
          'Довёл трёх потенциальных клиентов до предварительного коммерческого расчёта через ознакомительные звонки; вёл шесть тёплых контактов, включая AKFA Group — Узбекистан, больше 30 000 сотрудников.',
        ],
        m: [
          { v: '677', l: 'предприятий охвачено' },
          { v: '313', l: 'откликов при плане 300' },
          { v: '275', l: 'содержательных ответов' },
          { v: '6', l: 'тёплых контактов' },
        ],
      },
      {
        t: 'AGORA Global Business Club',
        img: 'work-agora.jpg',
        imgAlt: 'Форум AGORA, отель Soluxe',
        sub: 'Международный деловой форум',
        meta: 'январь — апрель 2026 · отель Soluxe, Москва',
        role: 'Руководитель продаж форума',
        d: 'Руководил продажами международного делового форума 25–26 апреля 2026 года со стороны Consult Invest ITIC как партнёра-исполнителя AGORA.',
        b: [
          'Вёл всю переписку и общение с иностранными гостями на английском языке, включая индийскую и южноафриканскую делегации.',
          'Нашёл четырёх заинтересованных предпринимателей на площадке форума.',
          'Форум освещали «Россия-1», НТВ и RuNews24.',
        ],
        m: [
          { v: '2', l: 'иностранные делегации' },
          { v: '4', l: 'заинтересованных клиента' },
          { v: '3', l: 'федеральных СМИ' },
        ],
      },
    ],
  },

  current: {
    n: '05',
    kicker: 'В работе сейчас',
    title: '2026 год',
    intro: 'Проекты, которые веду прямо сейчас.',
    items: [
      {
        t: 'Международный фестиваль молодёжи 2026',
        meta: 'Екатеринбург · 11–17 сентября 2026',
        d: 'Координирую делегацию Бразилии в детской программе фестиваля: 10 000 участников из 191 страны, из них 1 000 подростков от 14 до 17 лет. Веду всю переписку с бразильской стороной на португальском, собираю и проверяю документы участников, отвечаю за логистику и сопровождение группы в России.',
      },
      {
        t: 'Our Generation 2026',
        meta: 'Международный детский песенный конкурс',
        d: 'Перевёл на португальский язык весь пакет конкурсных документов: регламент, брифинг для делегаций, анкету участника и требования к конкурсным номерам. Договорился об участии бразильского члена жюри и подобрал исполнителя, который представит страну в финале.',
      },
      {
        t: 'Интервидение-2026',
        meta: 'Эр-Рияд, Саудовская Аравия · декабрь 2026',
        d: 'Занимаюсь организацией конкурса. В 2025 году провёл на нём делегации пяти стран.',
      },
      {
        t: 'Бизнес-инкубатор БРИКС',
        meta: 'Очная программа 2027–2028',
        d: 'Подготовил обращение в Министерство туризма Бразилии о грантовой поддержке очной программы.',
      },
      {
        t: 'Cifrex',
        meta: 'Беспилотные авиационные системы',
        d: 'Перевёл на португальский язык документацию по аппаратам UAV 30E, 45 и 440M и по комплексу Droneport.',
      },
    ],
  },

  career: {
    n: '06',
    kicker: 'Опыт и образование',
    title: 'Хронология',
    timelineTitle: 'Занятость по месяцам',
    timelineNote: 'Часть проектов шла параллельно с основной работой.',
    timelineFrom: '2024-04',
    timelineTo: '2026-12',
    ongoing: 'по настоящее время',
    nowLabel: 'сейчас',
    legendRole: 'Должности',
    legendProject: 'Проекты',
    timeline: [
      { t: 'Consult Invest ITIC', from: '2025-08', to: null, kind: 'role' },
      { t: 'Финансовый консультант', from: '2024-08', to: '2025-12', kind: 'role' },
      { t: 'Атташе и переводчик', from: '2024-04', to: '2025-04', kind: 'role' },
      { t: 'Интервидение-2025', from: '2025-08', to: '2025-09', kind: 'project' },
      { t: 'Бизнес-инкубатор ШОС', from: '2025-09', to: '2025-12', kind: 'project' },
      { t: 'Russia Bridge Program', from: '2025-11', to: '2025-12', kind: 'project' },
      { t: 'RAKEZ', from: '2026-01', to: '2026-05', kind: 'project' },
      { t: 'AGORA', from: '2026-01', to: '2026-04', kind: 'project' },
    ],
    jobsTitle: 'Опыт работы',
    jobs: [
      {
        org: 'Consult Invest ITIC',
        note: 'Международная торгово-инвестиционная консалтинговая компания',
        period: 'август 2025 — настоящее время',
        role: 'Руководитель российского офиса (Country Manager, Russia)',
        sub: 'Генеральный директор юридически с января 2026 · менеджер международных коммерческих проектов, август — декабрь 2025',
        b: [
          'Руковожу российским направлением компании, представленной в шести странах БРИКС, ШОС и Персидского залива. Отвечаю за привлечение клиентов, реализацию проектов и работу с государственными структурами в России и СНГ.',
          'Закрыл пробел в документации, доставшийся от прежнего руководства: подготовил агентский договор и акт выполненных работ по запуску офиса в Шэньчжэне, работая напрямую с исходными документами на китайском и английском языке.',
          'Выстроил с нуля кадровое делопроизводство и комплаенс — правила внутреннего трудового распорядка, трудовые договоры, документы по охране труда — и ввёл в работу новых сотрудников.',
          'Представляю компанию на закрытых деловых мероприятиях: Greenwood Business Park, клуб «Атланты», партнёрские форумы.',
        ],
      },
      {
        org: 'Финансовый консультант',
        note: 'Личное финансовое планирование и инвестиционный консалтинг',
        period: 'август 2024 — декабрь 2025',
        role: 'Частная практика',
        b: [
          'Вёл 20 клиентов: индивидуальные финансовые планы — постановка целей, формирование финансовой подушки, оптимизация бюджета и снижение долговой нагрузки. Целевого резерва достигли все клиенты.',
          'Собирал диверсифицированные портфели по принципам портфельной теории, включая долю золота. Средняя доходность клиентов в 2025 году — плюс 5% на фоне снижавшегося российского рынка акций.',
          'Структурировал долгосрочные накопления через инвестиционное страхование жизни и инструменты краткосрочного роста — фонды денежного рынка и облигации.',
        ],
      },
      {
        org: 'Атташе и переводчик',
        note: 'Международные форумы в Москве',
        period: 'апрель 2024 — апрель 2025',
        role: 'Бразильская делегация',
        b: [
          'Атташе бразильской делегации на мероприятиях Росконгресса и МГИМО, Рабочая группа БРИКС.',
          'Устный переводчик на II Международном антифашистском форуме, апрель 2025 года, 91 страна.',
        ],
      },
    ],
    eduTitle: 'Образование',
    edu: [
      {
        org: 'МГИМО МИД России',
        period: '2026 — 2028',
        role: 'Магистратура, «Экономика»',
        d: 'Специализация: международный финансовый анализ, учёт и аудит.',
      },
      {
        org: 'МГИМО МИД России',
        period: '2022 — 2026',
        role: 'Бакалавриат, «Международные отношения», с отличием',
        d: 'Диплом со знанием иностранных языков: первый — португальский, второй — английский. Дипломная работа: «Экономическая дипломатия Бразилии как инструмент продвижения и реализации внешнеполитических целей в Латинской Америке».',
      },
      {
        org: 'Федеральный университет Минас-Жерайс (UFMG)',
        period: 'июль 2025',
        role: 'Летняя школа по бразилистике',
        d: 'Интенсивная программа в одном из трёх ведущих университетов Бразилии, поток продвинутого уровня португальского языка.',
      },
    ],
    langTitle: 'Языки',
    langs: [
      { l: 'Русский', v: 'родной', lvl: 4, cap: 'Родной' },
      { l: 'Португальский', v: 'дипломатическая, юридическая и коммерческая лексика', lvl: 3, cap: 'C1' },
      { l: 'Английский', v: 'свободное профессиональное владение', lvl: 3, cap: 'C1' },
      { l: 'Испанский', v: 'рабочий уровень', lvl: 2, cap: 'B1' },
    ],
    skillTitle: 'Навыки',
    skills: [
      { k: 'Развитие бизнеса', v: 'Привлечение клиентов, работа с базой контактов, продажи в сегменте B2B' },
      { k: 'Выход на рынки', v: 'Исследование рынка, финансовое моделирование, конкурентный анализ, стратегия выхода' },
      { k: 'Международные отношения', v: 'Дипломатический протокол, работа с государственными структурами, многосторонние переговоры' },
      { k: 'Управление проектами', v: 'Организация мероприятий, координация смежных команд, работа с подрядчиками и в сжатые сроки' },
      { k: 'Финансовый анализ', v: 'Корпоративные финансы, юнит-экономика, финансовая отчётность, формирование инвестиционного портфеля' },
      { k: 'Работа с документами', v: 'Коммерческие предложения, договоры оказания услуг, агентские договоры, закрывающие и первичные документы' },
    ],
  },

  contact: {
    n: '07',
    kicker: 'Контакты',
    title: 'Готов обсудить задачу или позицию',
    d: 'Отвечаю лично. Если вопрос по международному проекту, напишите сразу суть, страну и сроки — так будет быстрее.',
    phoneLabel: 'Телефон',
    emailLabel: 'Почта',
    tgLabel: 'Telegram',
    cityLabel: 'Город',
    city: 'Москва, Россия',
    note: 'Рекомендации и подтверждающие материалы предоставляются по запросу.',
  },

  footer: {
    rights: 'Евгений Шутов. Все права защищены.',
    navTitle: 'Разделы',
    contactTitle: 'Связь',
  },
};

export const en = {
  lang: 'en',
  dir: 'ltr',
  altLang: 'ru',
  altLabel: 'Русский',
  altHref: '/',
  homeHref: '/en/',
  title: 'Evgeny Shutov. International projects, delegations and business events',
  description:
    'International affairs specialist, MGIMO. Latin America; Portuguese and English at C1. Foreign delegations and protocol, international event management, contracts and state-contract reporting.',
  ogLocale: 'en_US',

  brand: 'Shutov',
  skip: 'Skip to content',
  menu: 'Menu',
  close: 'Close',
  cvLabel: 'CV in PDF',

  nav: [
    { href: '#profile', label: 'About', n: '01' },
    { href: '#practice', label: 'Practice', n: '02' },
    { href: '#geo', label: 'Geography', n: '03' },
    { href: '#work', label: 'Projects', n: '04' },
    { href: '#current', label: '2026', n: '05' },
    { href: '#career', label: 'Experience', n: '06' },
    { href: '#contact', label: 'Contact', n: '07' },
  ],

  hero: {
    eyebrow: 'Evgeny Shutov',
    lead: 'International projects,',
    leadEm: 'delegations',
    leadTail: 'and business events',
    para:
      'Country Manager for Russia at Consult Invest ITIC. Latin America; Portuguese and English at C1, negotiating without an interpreter.',
    ctaPrimary: 'Get in touch',
    ctaSecondary: 'See the projects',
    portraitAlt: 'Evgeny Shutov',
  },

  figures: {
    eyebrow: 'Verifiable results',
    items: [
      { value: '45', unit: 'people', label: 'Across five national delegations at Intervision 2025, which I ran from invitation to departure' },
      { value: '134', unit: 'countries', label: 'Signal reach of the Brazilian broadcast, which I arranged single-handedly' },
      { value: '9', unit: 'M ₽', label: 'State-contract expenditure that I reconciled into a report backed by source documents' },
      { value: '677', unit: 'companies', label: 'Reached across Russia, Uzbekistan and Kazakhstan against a plan of 300-400 over three months' },
    ],
  },

  profile: {
    n: '01',
    kicker: 'About',
    title: 'I work where the conversation has to happen without an interpreter',
    paras: [
      'An international project rests on three things: a signed agreement, a delegation that arrives and leaves without a hitch, and a report the state client accepts. I am accountable for all three.',
      'Portuguese is my main working language: MGIMO, first foreign language, C1 across diplomatic, legal and commercial vocabulary. I speak to the Latin American side directly, without an interpreter, and that noticeably shortens approval timelines.',
      'The other half of the work is operational and financial: visit programmes, visas, contractors, venues, payment processing, closing documents and reporting. I am equally at ease negotiating with a ministry and reconciling source documents worth nine million roubles.',
    ],
    facts: [
      {
        k: 'Education',
        v: 'MGIMO, International Relations, BA with honours. MA in Economics: international financial analysis, accounting and audit.',
      },
      {
        k: 'Languages',
        v: 'Portuguese C1, English C1, Spanish B1. Summer school in Brazilian studies at the Federal University of Minas Gerais.',
      },
      {
        k: 'Region',
        v: 'Latin America, Brazil above all. Thesis on Brazilian economic diplomacy as an instrument of foreign policy.',
      },
      {
        k: 'Track record',
        v: 'Television, government agencies and private companies. Projects run under presidential decree, with Foreign Ministry support and under state contracts.',
      },
    ],
  },

  practice: {
    n: '02',
    kicker: 'Practice',
    title: 'What I do',
    intro: 'Five areas. Each one is backed by completed projects, not just lines in a job description.',
    items: [
      {
        t: 'Foreign delegations and protocol',
        d: 'Accompanying a delegation from the first letter to a ministry through to the group’s departure.',
        b: ['Co-organiser agreements with national governments', 'Visa support, accommodation, transport', 'Visit programmes and delegation attachés', 'Work with embassies and government agencies'],
      },
      {
        t: 'International event management',
        d: 'Forums, contests and acceleration programmes: the full cycle from concept to closing documents.',
        b: ['Business programme and participant selection', 'Sales and participant recruitment', 'Venue, accommodation, contractors', 'Payment processing and contract base'],
      },
      {
        t: 'Contracts, procurement and reporting',
        d: 'Project paperwork, from contractor agreements to the final report under a state contract.',
        b: ['Reporting under state contracts', 'Reconciliation of contractor agreements and source documents', 'Agency agreements, acts, commercial proposals', 'HR administration and compliance'],
      },
      {
        t: 'Business development and market entry',
        d: 'Client acquisition across Russia and the CIS against measurable targets.',
        b: ['Lead generation and cold outreach', 'CRM built per country', 'Market research and competitive analysis', 'Financial modelling and unit economics'],
      },
      {
        t: 'Language and translation',
        d: 'Portuguese and English across diplomatic, legal, commercial and technical vocabulary.',
        b: ['Consecutive interpreting at forums', 'Translation of contracts, regulations and statutory documents', 'Technical documentation', 'Business and diplomatic correspondence'],
      },
    ],
  },

  geo: {
    n: '03',
    kicker: 'Geography',
    title: 'Where I have worked',
    intro: 'Twelve countries where I have run projects, negotiations or delegations. The numbers on the map match the numbers in the list.',
    legendMarked: 'Project countries',
    legendRest: 'Rest of the world',
    items: [
      { key: 'Brazil', name: 'Brazil', note: 'Intervision delegation, the Brazilian television broadcast, the youth festival, the application to the Ministry of Tourism' },
      { key: 'Russia', name: 'Russia', note: 'Base, Moscow. The Russian practice of Consult Invest ITIC, forums and state contracts' },
      { key: 'United Arab Emirates', name: 'UAE', note: 'Intervision 2025 delegation; Ras Al Khaimah Economic Zone' },
      { key: 'Saudi Arabia', name: 'Saudi Arabia', note: 'Russia Bridge Program, Intervision 2026 in Riyadh' },
      { key: 'Ethiopia', name: 'Ethiopia', note: 'Intervision 2025 delegation' },
      { key: 'Kenya', name: 'Kenya', note: 'Intervision 2025 delegation' },
      { key: 'Madagascar', name: 'Madagascar', note: 'Intervision 2025 delegation' },
      { key: 'China', name: 'China', note: 'Documentation for the launch of the Shenzhen office' },
      { key: 'Uzbekistan', name: 'Uzbekistan', note: 'Client acquisition for RAKEZ, work with AKFA Group' },
      { key: 'Kazakhstan', name: 'Kazakhstan', note: 'Client acquisition for RAKEZ' },
      { key: 'India', name: 'India', note: 'AGORA forum delegation' },
      { key: 'South Africa', name: 'South Africa', note: 'AGORA forum delegation' },
    ],
  },

  work: {
    n: '04',
    kicker: 'Selected projects',
    title: 'What has been delivered',
    items: [
      {
        t: 'Intervision 2025',
        img: 'work-intervision.jpg',
        imgAlt: 'Delegations at Intervision 2025',
        sub: 'International music contest',
        meta: 'August-September 2025 · Live Arena, Moscow',
        role: 'Project manager, national delegations',
        d: 'I joined the project less than a month before the contest as a Portuguese-speaking specialist. The contest was held under presidential decree with the support of the Russian Foreign Ministry, in a 20,000-seat arena.',
        b: [
          'Five national delegations totalling 45 people: Brazil, Madagascar, Kenya, Ethiopia and the UAE.',
          'Co-organiser agreements with national governments, visa support, accommodation, transport and a ten-day visit programme.',
          'Selected and supervised five delegation attachés, one per country.',
          'Conducted all work with the Brazilian side in Portuguese: the artist, the production team, the broadcaster and the ministry of culture.',
          'Arranged the broadcast of the contest on Brazilian television single-handedly: prepared and translated the broadcaster’s document package: the organisation’s charter, HR documents, agreements and memoranda.',
        ],
        m: [
          { v: '45', l: 'delegation members' },
          { v: '5', l: 'countries' },
          { v: '3M+', l: 'broadcast viewers' },
          { v: '134', l: 'countries reached' },
        ],
      },
      {
        t: 'SCO Business Incubator 2025',
        img: 'work-sco.jpg',
        imgAlt: 'SCO Business Incubator, Omsk',
        sub: 'State contract: reporting and financial audit',
        meta: 'September-December 2025 · programme held in Omsk',
        role: 'Head of reporting under the state contract',
        d: 'Client: the Directorate of the World Youth Festival. The programme ran on 19-23 August 2025, with more than 100 participants from all ten SCO member states.',
        b: [
          'Final report of more than 3,000 pages: collected, structured and formatted training materials across 25 workshop sessions.',
          'Wrote summaries and handouts for roughly 12 sessions from scratch, because no source materials existed.',
          'Handled financial reporting single-handedly: reconciled around 10 contractor agreements covering interpreters, catering, staff and logistics.',
          'Agreed document corrections with suppliers and produced a fully balanced expense report of 9 million roubles, backed by source documents and internal orders.',
        ],
        m: [
          { v: '3,000+', l: 'pages of report' },
          { v: '9M ₽', l: 'reconciled' },
          { v: '25', l: 'workshop sessions' },
          { v: '10', l: 'SCO member states' },
        ],
      },
      {
        t: 'Russia Bridge Program',
        img: 'work-bridge.jpg',
        imgAlt: 'Russia Bridge Program, Moscow',
        sub: 'First Russian-Saudi business acceleration programme',
        meta: 'November-December 2025 · Moscow',
        role: 'Co-organiser',
        d: 'The programme ran on 4-5 December 2025 with more than 60 participants. It was opened by Leonid Slutsky, Chairman of the State Duma Committee on International Affairs, and the Ambassador of Saudi Arabia.',
        b: [
          'Sales and outreach: around 200 calls and some 1,000 impressions across Telegram and the web.',
          'Brought in 30 paying participants and arranged 15 business meetings between Russian and foreign companies.',
          'Selected 9 Russian projects for the pitch session; three received direct investment support and a commercial licence fee waiver from the venture fund Value Makers Studio.',
          'Negotiated venue and accommodation contracts with Moscow hotels, securing below-market rates and additional discounts.',
          'Set up payment processing and prepared commercial proposal templates and service agreements.',
          'Handled all correspondence and negotiation with the visiting Saudi delegation in English.',
        ],
        m: [
          { v: '60+', l: 'participants' },
          { v: '30', l: 'paying participants' },
          { v: '15', l: 'business meetings' },
          { v: '3', l: 'projects funded' },
        ],
      },
      {
        t: 'RAKEZ',
        img: 'work-rakez.jpg',
        imgAlt: 'RAKEZ project work',
        sub: 'Ras Al Khaimah Economic Zone, UAE · Russia and CIS markets',
        meta: 'January-May 2026',
        role: 'Client acquisition and single point of contact',
        d: 'Responsible for client acquisition across Russia and the CIS for the UAE free economic zone, and the single point of contact for all Russian and CIS counterparties on behalf of RAKEZ.',
        b: [
          'Reached around 677 companies across Russia, Uzbekistan and Kazakhstan against a plan of 300-400 over three months.',
          'Generated around 313 responses expressing initial interest against a target of 300.',
          'Designed and ran a cold outreach campaign: 512 selected companies, around 275 substantive replies.',
          'Built a separate client base for each of the three countries.',
          'Advanced three prospects to preliminary quotation through discovery calls; maintained six warm contacts, including AKFA Group in Uzbekistan, which has more than 30,000 employees.',
        ],
        m: [
          { v: '677', l: 'companies reached' },
          { v: '313', l: 'responses vs target 300' },
          { v: '275', l: 'substantive replies' },
          { v: '6', l: 'warm contacts' },
        ],
      },
      {
        t: 'AGORA Global Business Club',
        img: 'work-agora.jpg',
        imgAlt: 'AGORA forum, Soluxe Hotel',
        sub: 'International business forum',
        meta: 'January-April 2026 · Soluxe Hotel, Moscow',
        role: 'Head of forum sales',
        d: 'Led sales for the international business forum of 25-26 April 2026 on behalf of Consult Invest ITIC, AGORA’s delivery partner.',
        b: [
          'Handled all correspondence and communication with foreign guests in English, including the Indian and South African delegations.',
          'Found four interested entrepreneurs at the forum itself.',
          'The forum was covered by Rossiya-1, NTV and RuNews24.',
        ],
        m: [
          { v: '2', l: 'foreign delegations' },
          { v: '4', l: 'interested clients' },
          { v: '3', l: 'federal media outlets' },
        ],
      },
    ],
  },

  current: {
    n: '05',
    kicker: 'Currently running',
    title: 'The 2026 slate',
    intro: 'Projects I am running right now.',
    items: [
      {
        t: 'International Youth Festival 2026',
        meta: 'Yekaterinburg · 11-17 September 2026',
        d: 'Coordinating the Brazilian delegation within the festival’s children’s programme: 10,000 participants from 191 countries, including 1,000 teenagers aged 14 to 17. All correspondence with the Brazilian side in Portuguese, collection and verification of participant documents, logistics and accompaniment of the group in Russia.',
      },
      {
        t: 'Our Generation 2026',
        meta: 'International children’s song contest',
        d: 'Translated the full package of competition documents into Portuguese: regulations, delegation briefing, participant form and performance requirements. Secured the participation of a Brazilian jury member and selected the performer who will represent the country in the final.',
      },
      {
        t: 'Intervision 2026',
        meta: 'Riyadh, Saudi Arabia · December 2026',
        d: 'Working on the organisation of the contest. In 2025 I ran five national delegations through it.',
      },
      {
        t: 'BRICS Business Incubator',
        meta: 'In-person programme 2027-2028',
        d: 'Prepared the application to the Brazilian Ministry of Tourism for grant support of the in-person programme.',
      },
      {
        t: 'Cifrex',
        meta: 'Unmanned aerial systems',
        d: 'Translated documentation into Portuguese for the UAV 30E, 45 and 440M aircraft and the Droneport complex.',
      },
    ],
  },

  career: {
    n: '06',
    kicker: 'Experience and education',
    title: 'Chronology',
    timelineTitle: 'Month by month',
    timelineNote: 'Several projects ran in parallel with the main role.',
    timelineFrom: '2024-04',
    timelineTo: '2026-12',
    ongoing: 'to date',
    nowLabel: 'now',
    legendRole: 'Roles',
    legendProject: 'Projects',
    timeline: [
      { t: 'Consult Invest ITIC', from: '2025-08', to: null, kind: 'role' },
      { t: 'Financial adviser', from: '2024-08', to: '2025-12', kind: 'role' },
      { t: 'Attaché and interpreter', from: '2024-04', to: '2025-04', kind: 'role' },
      { t: 'Intervision 2025', from: '2025-08', to: '2025-09', kind: 'project' },
      { t: 'SCO Business Incubator', from: '2025-09', to: '2025-12', kind: 'project' },
      { t: 'Russia Bridge Program', from: '2025-11', to: '2025-12', kind: 'project' },
      { t: 'RAKEZ', from: '2026-01', to: '2026-05', kind: 'project' },
      { t: 'AGORA', from: '2026-01', to: '2026-04', kind: 'project' },
    ],
    jobsTitle: 'Experience',
    jobs: [
      {
        org: 'Consult Invest ITIC',
        note: 'International trade, investment and consulting company',
        period: 'August 2025 to present',
        role: 'Country Manager, Russia',
        sub: 'Legally appointed general director from January 2026 · manager of international commercial projects, August-December 2025',
        b: [
          'I head the Russian practice of a company present in six countries across BRICS, the SCO and the Gulf. I am responsible for client acquisition, project delivery and work with government bodies across Russia and the CIS.',
          'Closed a documentation gap inherited from previous management: prepared the agency agreement and completion act for the launch of the Shenzhen office, working directly with source documents in Chinese and English.',
          'Built HR administration and compliance from scratch, covering internal labour regulations, employment contracts and occupational safety documentation, then brought new staff into the system.',
          'Represent the company at closed business events: Greenwood Business Park, the Atlanty club, partner forums.',
        ],
      },
      {
        org: 'Financial adviser',
        note: 'Personal financial planning and investment consulting',
        period: 'August 2024 to December 2025',
        role: 'Private practice',
        b: [
          'Advised 20 clients: individual financial plans covering goal setting, emergency fund formation, budget optimisation and debt reduction. Every client reached their target reserve.',
          'Built diversified portfolios on portfolio-theory principles, including a gold allocation. Average client return in 2025 was plus 5% against a declining Russian equity market.',
          'Structured long-term savings through unit-linked insurance products and short-term growth instruments such as money market funds and bonds.',
        ],
      },
      {
        org: 'Attaché and interpreter',
        note: 'International forums in Moscow',
        period: 'April 2024 to April 2025',
        role: 'Brazilian delegation',
        b: [
          'Attaché to the Brazilian delegation at Roscongress and MGIMO events, BRICS Working Group.',
          'Consecutive interpreter at the II International Anti-Fascist Forum, April 2025, 91 countries.',
        ],
      },
    ],
    eduTitle: 'Education',
    edu: [
      {
        org: 'MGIMO University',
        period: '2026-2028',
        role: 'MA, Economics',
        d: 'Specialisation: international financial analysis, accounting and audit.',
      },
      {
        org: 'MGIMO University',
        period: '2022-2026',
        role: 'BA, International Relations, with honours',
        d: 'Degree with foreign languages: Portuguese as first language, English as second. Thesis: “Brazilian economic diplomacy as an instrument for advancing and implementing foreign policy objectives in Latin America”.',
      },
      {
        org: 'Federal University of Minas Gerais (UFMG)',
        period: 'July 2025',
        role: 'Summer school in Brazilian studies',
        d: 'Intensive programme at one of Brazil’s three leading universities, advanced Portuguese stream.',
      },
    ],
    langTitle: 'Languages',
    langs: [
      { l: 'Russian', v: 'native', lvl: 4, cap: 'Native' },
      { l: 'Portuguese', v: 'diplomatic, legal and commercial vocabulary', lvl: 3, cap: 'C1' },
      { l: 'English', v: 'full professional proficiency', lvl: 3, cap: 'C1' },
      { l: 'Spanish', v: 'working proficiency', lvl: 2, cap: 'B1' },
    ],
    skillTitle: 'Skills',
    skills: [
      { k: 'Business development', v: 'Client acquisition, contact base management, B2B sales' },
      { k: 'Market entry', v: 'Market research, financial modelling, competitive analysis, entry strategy' },
      { k: 'International affairs', v: 'Diplomatic protocol, government relations, multilateral negotiation' },
      { k: 'Project management', v: 'Event delivery, cross-team coordination, contractor management, tight deadlines' },
      { k: 'Financial analysis', v: 'Corporate finance, unit economics, financial reporting, investment portfolio construction' },
      { k: 'Documentation', v: 'Commercial proposals, service agreements, agency agreements, closing and source documents' },
    ],
  },

  contact: {
    n: '07',
    kicker: 'Contact',
    title: 'Open to a brief or a position',
    d: 'I reply personally. For an international project, lead with the substance, the country and the timeline. That will be quickest.',
    phoneLabel: 'Phone',
    emailLabel: 'Email',
    tgLabel: 'Telegram',
    cityLabel: 'Based in',
    city: 'Moscow, Russia',
    note: 'References and supporting materials available on request.',
  },

  footer: {
    rights: 'Evgeny Shutov. All rights reserved.',
    navTitle: 'Sections',
    contactTitle: 'Contact',
  },
};
